### ISSUE TITLE
/run/aid/events gets removed after reboot, resulting in socket error

### ISSUE THREAD

**Issue by irathore** [noironetworks/neutron#3]
'/run' is volatile. After rebooting my controller I noticed the neutron ACI sync is not working. Found this error

2017-01-11 17:13:16.625 871 INFO aim.agent.aid.event_handler [-] Connect to socket /run/aid/events/aid.sock
2017-01-11 17:13:16.626 871 DEBUG aim.agent.aid.event_handler [-] Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/aim/agent/aid/event_handler.py", line 115, in _listener
    self._connect()
  File "/usr/lib/python2.7/site-packages/aim/agent/aid/event_handler.py", line 106, in _connect
    self.sock.bind(self.us_path)
  File "<string>", line 1, in bind
error: [Errno 2] No such file or directory

**Comment by ivar-lazzaro** [comment]
Is AID running? AID should created that file upon restart.

Ivar.

**Comment by amittbose** [comment]
The socket file will be created by AID, but it expects the the parent directories (/run/aid and /run/aid/events) to be present (which are obviously not there anymore).

**Comment by irathore** [comment]
That is correct. Creating /run/aid/events fixes the issue.

**Comment by mandeepdhami** [comment]
Should this be fixed in the systemd file as a pre-condition?
